spring:
  datasource:
    url: ${ POSTGRES_URI }
    username: ${ POSTGRES_USERNAME }
    password: ${ POSTGRES_PASSWORD }
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect
